//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ChitietGH
{
    public int MaSP { get; set; }
    public int MaGH { get; set; }
    public Nullable<int> Soluong { get; set; }
    public Nullable<decimal> Gia { get; set; }
}

public partial class Dangky
{
    public string TenDN { get; set; }
    public string MatKhau { get; set; }
    public string Email { get; set; }
    public string DiaChi { get; set; }
    public string TenDayDu { get; set; }
    public string NgaySinh { get; set; }
    public Nullable<int> MaQuyen { get; set; }
}

public partial class DanhMucHang
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DanhMucHang()
    {
        this.SanPhamDMs = new HashSet<SanPhamDM>();
    }

    public int MaDM { get; set; }
    public string TenDM { get; set; }
    public string AnhDaiDien { get; set; }
    public Nullable<int> ThuTu { get; set; }
    public Nullable<int> MaDMCha { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SanPhamDM> SanPhamDMs { get; set; }
}

public partial class Giohang
{
    public int ID { get; set; }
    public Nullable<int> MaKH { get; set; }
    public Nullable<int> MaSP { get; set; }
    public Nullable<int> Soluong { get; set; }
    public Nullable<decimal> DonGia { get; set; }

    public virtual Khachhang Khachhang { get; set; }
    public virtual SanPhamDM SanPhamDM { get; set; }
}

public partial class Khachhang
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Khachhang()
    {
        this.Giohangs = new HashSet<Giohang>();
    }

    public int ID { get; set; }
    public string TenKH { get; set; }
    public string Matkhau { get; set; }
    public string SDT { get; set; }
    public string Diachi { get; set; }
    public string Email { get; set; }
    public Nullable<int> MaQuyen { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Giohang> Giohangs { get; set; }
}

public partial class Lienhe
{
    public int MaLH { get; set; }
    public string TenKH { get; set; }
    public string Email { get; set; }
    public string Tieude { get; set; }
    public string Noidung { get; set; }
}

public partial class Phanquyen
{
    public int Maquyen { get; set; }
    public string TenQuyen { get; set; }
}

public partial class SanPhamDM
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SanPhamDM()
    {
        this.Giohangs = new HashSet<Giohang>();
    }

    public int MaSP { get; set; }
    public string TenSP { get; set; }
    public string HinhAnh { get; set; }
    public string Mota { get; set; }
    public Nullable<int> Soluong { get; set; }
    public Nullable<decimal> Gia { get; set; }
    public Nullable<int> MaDM { get; set; }

    public virtual DanhMucHang DanhMucHang { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Giohang> Giohangs { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}
