//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class QuanlyBanHangEntities2 : DbContext
{
    public QuanlyBanHangEntities2()
        : base("name=QuanlyBanHangEntities2")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<ChitietGH> ChitietGHs { get; set; }
    public virtual DbSet<Dangky> Dangkies { get; set; }
    public virtual DbSet<DanhMucHang> DanhMucHangs { get; set; }
    public virtual DbSet<Giohang> Giohangs { get; set; }
    public virtual DbSet<Khachhang> Khachhangs { get; set; }
    public virtual DbSet<Lienhe> Lienhes { get; set; }
    public virtual DbSet<Phanquyen> Phanquyens { get; set; }
    public virtual DbSet<SanPhamDM> SanPhamDMs { get; set; }
    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
}
